'use client';
import {useEffect,useState} from 'react';
import {SiteFooter} from '../site-info';
import {compatibility} from '../../lib/compatibility.mjs';
import {DEMO_EMAIL,DEMO_PASSWORD,demoLogin,demoProfile,demoTeammates} from '../../lib/pages-demo.mjs';

const sessionKey='valotribe-fictional-login-v1';
const formatTime=(value:number)=>`${String(Math.floor(value/60)%24).padStart(2,'0')}:${String(value%60).padStart(2,'0')}`;
const minutes=(value:string)=>{const [h,m]=value.split(':').map(Number);return h*60+m};
type Post={id:string;title:string;author:string;mine:boolean};
const initialPosts:Post[]=[{id:'fictional-post',title:'Evening Mumbai practice — looking for an Initiator',author:'Demo Controller',mine:false}];

export default function LoginDashboard(){
 const [signedIn,setSignedIn]=useState(false),[ready,setReady]=useState(false),[error,setError]=useState('');
 const [tab,setTab]=useState('Dashboard'),[profile,setProfile]=useState({...demoProfile}),[posts,setPosts]=useState(initialPosts),[notice,setNotice]=useState('');
 useEffect(()=>{try{setSignedIn(sessionStorage.getItem(sessionKey)==='signed-in')}catch{}setReady(true)},[]);
 function signOut(){try{sessionStorage.removeItem(sessionKey)}catch{}setSignedIn(false);setProfile({...demoProfile});setPosts(initialPosts);setTab('Dashboard');setError('');setNotice('')}
 function login(event:React.FormEvent<HTMLFormElement>){event.preventDefault();const form=new FormData(event.currentTarget);if(!demoLogin(form.get('email'),form.get('password'))){setError('Incorrect demo email or password. Use the credentials shown below.');return}try{sessionStorage.setItem(sessionKey,'signed-in')}catch{}setError('');setSignedIn(true)}
 const matches=demoTeammates.map(player=>({player,match:compatibility(profile,player)}));
 return <main><header><a className="brand" href="/">Valo<span>Tribe</span></a><span className="demo">FICTIONAL DEMO ACCOUNT</span>{signedIn?<div className="account"><span>{profile.name}</span><button className="secondary" onClick={signOut}>Sign out</button></div>:<a href="/demo">Explore demo</a>}</header>
 {!ready?<section className="auth" aria-live="polite">Loading demo…</section>:!signedIn?<section className="auth"><p className="eyebrow">FIND THE TRIBE THAT MATCHES YOUR VIBE</p><h1>Your next stack<br/>starts <em>here.</em></h1><p className="intro">Sign in to explore your personal dashboard, edit your Passport and find fictional teammates.</p><div className="notice"><strong>Demo login</strong><p>Email: <code>{DEMO_EMAIL}</code><br/>Password: <code>{DEMO_PASSWORD}</code></p><p>This is a browser simulation. No account is created and no email is sent. Use only the demo credentials.</p></div><form onSubmit={login}><label>Email<input name="email" type="email" required autoComplete="username" maxLength={254}/></label><label>Password<input name="password" type="password" required autoComplete="current-password" maxLength={128}/></label><button className="primary">Sign in</button>{error&&<p role="alert">{error}</p>}</form><p><a href="/demo">Preview without signing in</a> · <a href="/review">Reviewer guide</a></p></section>:<div className="shell"><aside><p className="eyebrow">YOUR PERSONAL DASHBOARD</p><nav aria-label="Main navigation">{['Dashboard','My Passport','Discover','LFG','Settings'].map(item=><button key={item} className={tab===item?'active':''} onClick={()=>{setTab(item);setNotice('')}}>{item}</button>)}</nav><div className="side-note">Find the tribe that<br/>matches your vibe.</div></aside><section className="content"><p className="notice">Fictional players and posts. Edits reset when you reload or sign out. Demo login lasts for this browser tab. No real authentication or database is connected.</p><div className="topline"><span>MUMBAI · INDIA</span><span>All play times / IST</span></div>
 {tab==='Dashboard'&&<><p className="eyebrow">WELCOME BACK</p><h1>Your next <em>tribe.</em></h1><p className="intro">Welcome, {profile.name}. Your personal dashboard is ready.</p><div className="cards"><article><h2>Your Passport</h2><p>{profile.rank} · {profile.roles.join(' / ')}</p><p>{profile.agents.join(' / ')}</p><p>{profile.languages.join(' / ')} · {formatTime(profile.start)}–{formatTime(profile.end)} IST</p><button className="primary" onClick={()=>setTab('My Passport')}>Edit My Passport</button></article><article><h2>Teammate discovery</h2><strong className="score">{matches.length}</strong><p>Fictional teammates available to explore.</p><button className="primary" onClick={()=>setTab('Discover')}>Discover teammates</button></article><article><h2>Looking for group</h2><p>{posts.length} fictional practice posts.</p><button className="primary" onClick={()=>setTab('LFG')}>Open LFG</button></article></div></>}
 {tab==='My Passport'&&<><p className="eyebrow">TEAMMATE PASSPORT</p><h1>Make it <em>yours.</em></h1><form className="profile-form" onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);setProfile({...profile,name:String(form.get('name')).trim(),rank:String(form.get('rank')),roles:[String(form.get('role'))],agents:String(form.get('agents')).split(',').map(x=>x.trim()).filter(Boolean),languages:String(form.get('languages')).split(',').map(x=>x.trim()).filter(Boolean),start:minutes(String(form.get('start'))),end:minutes(String(form.get('end'))),intent:String(form.get('intent')),visibility:String(form.get('visibility')),optedIn:form.get('visibility')==='PUBLIC'&&form.get('discovery')==='on'});setNotice('Demo Passport saved for this preview. No server data was changed.')}}><label>Display name<input name="name" required minLength={2} maxLength={40} defaultValue={profile.name}/></label><div className="two"><label>Rank<select name="rank" defaultValue={profile.rank}>{['Unranked','Iron','Bronze','Silver','Gold','Platinum','Diamond','Ascendant','Immortal','Radiant'].map(rank=><option key={rank}>{rank}</option>)}</select></label><label>Preferred role<select name="role" defaultValue={profile.roles[0]}>{['Controller','Duelist','Initiator','Sentinel'].map(role=><option key={role}>{role}</option>)}</select></label></div><label>Agents (comma-separated)<input name="agents" maxLength={310} defaultValue={profile.agents.join(', ')}/></label><label>Languages (comma-separated)<input name="languages" required maxLength={160} defaultValue={profile.languages.join(', ')}/></label><div className="two"><label>Usually start · IST<input name="start" type="time" required defaultValue={formatTime(profile.start)}/></label><label>Usually finish · IST<input name="end" type="time" required defaultValue={formatTime(profile.end)}/></label></div><label>Queue intent<select name="intent" defaultValue={profile.intent}><option>Competitive</option><option>Casual</option></select></label><label>Passport visibility<select name="visibility" defaultValue={profile.visibility}><option value="PRIVATE">Private</option><option value="PUBLIC">Public</option></select></label><label className="check"><input name="discovery" type="checkbox" defaultChecked={profile.optedIn}/>Appear in fictional discovery when public</label><button className="primary">Save Passport</button></form></>}
 {tab==='Discover'&&<><p className="eyebrow">BETTER TOGETHER</p><h1>Find your kind<br/><em>of teammate.</em></h1><p className="intro">These fictional matches use your current Passport preferences.</p><div className="cards">{matches.map(({player,match})=><article key={player.id}><div className="card-head"><div className="avatar">{player.name[0]}</div><div><h2>{player.name}</h2><small>{player.rank} · Fictional</small></div><strong className="score">{match.score}%<small>preference fit</small></strong></div><div className="tags">{player.roles.map(role=><span key={role}>{role}</span>)}</div><p>{player.agents.join(' / ')}</p><p>{match.sharedLanguages.join(' / ')||'No shared language'} · {match.overlap} min overlap</p><details><summary>Explain preference fit</summary>{match.factors.map(factor=><div className="factor" key={factor.label}><span>{factor.label}</span><strong>{Math.round(factor.weight*factor.value)} / {factor.weight}</strong></div>)}<p>Preference fit does not rate skill or conduct.</p></details></article>)}</div></>}
 {tab==='LFG'&&<><p className="eyebrow">LOOKING FOR GROUP</p><h1>Fill the <em>missing slots.</em></h1><p className="intro">Try creating a fictional practice post in this preview.</p>{profile.visibility==='PUBLIC'&&profile.optedIn?<form onSubmit={event=>{event.preventDefault();const form=new FormData(event.currentTarget);setPosts([...posts,{id:crypto.randomUUID(),title:String(form.get('title')).trim(),author:profile.name,mine:true}]);event.currentTarget.reset();setNotice('Fictional post created for this preview.')}}><label>Who do you want to queue with?<input name="title" required minLength={5} maxLength={160} placeholder="Looking for a Controller for tonight"/></label><button className="primary">Create demo post</button></form>:<p className="empty">Set your Passport to public and enable discovery to try posting.</p>}<div className="cards">{posts.map(post=><article key={post.id}><h2>{post.title}</h2><p>{post.author} · Mumbai · Fictional</p>{post.mine&&<button className="secondary" onClick={()=>setPosts(posts.filter(item=>item.id!==post.id))}>Delete my post</button>}</article>)}</div></>}
 {tab==='Settings'&&<><p className="eyebrow">DEMO ACCOUNT</p><h1>Your <em>choice.</em></h1><article><h2>Demo account details</h2><p>{DEMO_EMAIL}</p><p>The email is a fictional account label; ownership is not verified. Password recovery, email delivery and Riot linking are unavailable in this static preview.</p></article><article><h2>Reset the preview</h2><p>Restore the original Passport and fictional posts.</p><button className="secondary" onClick={()=>{setProfile({...demoProfile});setPosts(initialPosts);setNotice('Demo Passport and posts reset.')}}>Reset demo data</button></article><article><h2>End demo session</h2><button className="secondary" onClick={signOut}>Sign out</button></article></>}
 {notice&&<p className="notice" role="status">{notice}</p>}
 </section></div>}<SiteFooter/></main>
}
