import assert from 'node:assert/strict';
import {createRequire} from 'node:module';
import {spawn} from 'node:child_process';
import {mkdtemp,readFile,writeFile,readdir,rm,mkdir} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
const require=createRequire(join(process.cwd(),'package.json'));
const {PGlite}=require('@electric-sql/pglite'),{PGLiteSocketServer}=require('@electric-sql/pglite-socket'),{chromium}=require('playwright');
const temp=await mkdtemp(join(tmpdir(),'valotribe-browser-')),mail=join(temp,'mail'),mode=join(temp,'mode');await writeFile(mail,'');await writeFile(mode,'ok');
const db=await PGlite.create();for(const name of (await readdir('prisma/migrations')).filter(x=>x!=='migration_lock.toml').sort())await db.exec(await readFile(`prisma/migrations/${name}/migration.sql`,'utf8'));
const server=new PGLiteSocketServer({db,port:55436,host:'127.0.0.1'});await server.start();
const origin='http://127.0.0.1:3006',out=join(process.cwd(),'artifacts');await mkdir(out,{recursive:true});
const app=spawn(process.execPath,['--import','./scripts/test-mail.mjs',require.resolve('next/dist/bin/next'),'start','-p','3006','-H','127.0.0.1'],{env:{...process.env,APP_ORIGIN:origin,DATABASE_URL:'postgresql://postgres:postgres@127.0.0.1:55436/postgres?connection_limit=1&statement_cache_size=0&sslmode=disable',COOKIE_SECURE:'false',PUBLIC_SIGNUP_ENABLED:'true',OPERATOR_NAME:'Test Operator',SUPPORT_EMAIL:'support@example.test',RESEND_API_KEY:'test-only',EMAIL_FROM:'demo@example.test',TEST_MAIL_OUT:mail,TEST_MAIL_MODE:mode}});
let logs='';app.stdout.on('data',d=>logs+=d);app.stderr.on('data',d=>logs+=d);let browser;
try{
 for(let i=0;i<100;i++){try{if((await fetch(origin)).ok)break}catch{}await new Promise(r=>setTimeout(r,100));if(i===99)throw new Error(logs)}
 browser=await chromium.launch({headless:true});const page=await browser.newPage({viewport:{width:1440,height:1000}}),errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.goto(origin+'/demo');await page.getByLabel('Separately appear in discovery').waitFor();assert.equal(await page.getByLabel('Separately appear in discovery').isDisabled(),true);await page.getByLabel('Public Passport',{exact:true}).check();await page.getByLabel('Separately appear in discovery').check();await page.getByText('This fictional Passport would be discoverable.').waitFor();await page.getByRole('button',{name:'Discover',exact:true}).click();await page.getByRole('button',{name:'Explain preference fit'}).click();await page.getByText('240 minutes schedule overlap.').waitFor();await page.screenshot({path:out+'/valotribe-demo-desktop.png',fullPage:true});
 await page.getByRole('button',{name:'Riot consent',exact:true}).click();assert.equal(await page.getByRole('button',{name:'Simulate consent acknowledgment'}).isDisabled(),true);await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Simulate consent acknowledgment'}).click();await page.getByText('Preview complete. No Riot account was linked, verified or queried.').waitFor();
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:out+'/valotribe-demo-mobile.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),'Demo fits mobile viewport');
 await page.setViewportSize({width:1440,height:1000});await page.goto(origin);await page.getByLabel('Display name',{exact:true}).fill('Browser Tester');await page.getByLabel('Email',{exact:true}).fill('browser@example.test');await page.getByLabel('Password',{exact:true}).fill('browser-test-password-2026!');await page.getByRole('checkbox').check();await page.getByRole('button',{name:'Create account',exact:true}).last().click();await page.getByRole('heading',{name:'Make it yours.'}).waitFor();assert.equal(await page.getByRole('button',{name:'Discover',exact:true}).isDisabled(),true);
 const messages=(await readFile(mail,'utf8')).trim().split('\n').map(s=>JSON.parse(s)),url=messages[0].text.match(/http[^\s]+/)[0];await page.goto(url);await page.getByRole('heading',{name:'Verify your email'}).waitFor();await page.getByRole('button',{name:'Verify email',exact:true}).click();await page.getByText('Email verified. Return to the app.').waitFor();await page.getByRole('link',{name:'Back to ValoTribe'}).click();await page.getByLabel('Controller',{exact:true}).check();await page.getByLabel('Hindi',{exact:true}).check();await page.getByRole('button',{name:'Save and continue'}).click();await page.getByRole('heading',{name:'Find your kind of teammate.'}).waitFor();await page.getByRole('button',{name:'My Passport',exact:true}).click();await page.getByLabel('Passport visibility').selectOption('PUBLIC');await page.getByLabel('Appear in teammate discovery').check();await page.getByRole('button',{name:'Save Passport'}).click();await page.getByRole('heading',{name:'Find your kind of teammate.'}).waitFor();await page.getByRole('button',{name:'LFG',exact:true}).click();await page.getByLabel('Who do you want to queue with?').fill('Practice team for open qualifier trials');await page.getByRole('button',{name:'Create post'}).click();await page.getByRole('heading',{name:'Find your kind of teammate.'}).waitFor();await page.getByRole('button',{name:'LFG',exact:true}).click();await page.getByRole('heading',{name:'Practice team for open qualifier trials'}).waitFor();await page.getByRole('button',{name:'Settings',exact:true}).click();await page.getByRole('heading',{name:'Email verified',exact:true}).waitFor();await page.screenshot({path:out+'/valotribe-settings-desktop.png',fullPage:true});
 await page.setViewportSize({width:390,height:844});await page.screenshot({path:out+'/valotribe-settings-mobile.png',fullPage:true});assert.ok(await page.evaluate(()=>document.documentElement.scrollWidth<=window.innerWidth+1),'Settings fit mobile viewport');assert.deepEqual(errors,[]);console.log('Browser checks passed: fictional demo toggles, consent preview, desktop/mobile layout, signup, real email-link verification via intercepted mail, onboarding, public opt-in, saved LFG and Settings. No browser exceptions.');
}finally{if(browser)await browser.close();const exit=new Promise(r=>app.once('exit',r));app.kill('SIGTERM');await exit;await server.stop();await new Promise(r=>setTimeout(r,100));await db.close();await rm(temp,{recursive:true,force:true})}
