import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {PGLiteSocketServer} from '@electric-sql/pglite-socket';
import {readFile,writeFile,readdir,mkdtemp,rm} from 'node:fs/promises';
import {tmpdir} from 'node:os';
import {join} from 'node:path';
import {spawn} from 'node:child_process';
import {createRequire} from 'node:module';
const require=createRequire(import.meta.url),temp=await mkdtemp(join(tmpdir(),'valotribe-integration-'));
const mailFile=join(temp,'mail.jsonl'),modeFile=join(temp,'mode');await writeFile(mailFile,'');await writeFile(modeFile,'ok');
const db=await PGlite.create();
for(const migration of (await readdir('prisma/migrations')).filter(x=>x!=='migration_lock.toml').sort())await db.exec(await readFile(`prisma/migrations/${migration}/migration.sql`,'utf8'));
const server=new PGLiteSocketServer({db,port:55434,host:'127.0.0.1'});await server.start();
const origin='http://127.0.0.1:3005';
const env={...process.env,DATABASE_URL:'postgresql://postgres:postgres@127.0.0.1:55434/postgres?connection_limit=1&statement_cache_size=0&sslmode=disable',APP_ORIGIN:origin,COOKIE_SECURE:'false',PUBLIC_SIGNUP_ENABLED:'true',OPERATOR_NAME:'Test operator',SUPPORT_EMAIL:'support@example.test',RESEND_API_KEY:'test-key-never-sent',EMAIL_FROM:'ValoTribe <noreply@example.test>',TEST_MAIL_OUT:mailFile,TEST_MAIL_MODE:modeFile};
let logs='',app;
function start(overrides={}){app=spawn(process.execPath,['--import','./scripts/test-mail.mjs',require.resolve('next/dist/bin/next'),'start','-p','3005','-H','127.0.0.1'],{env:{...env,...overrides}});app.stdout.on('data',d=>logs+=d);app.stderr.on('data',d=>logs+=d);return app}
async function stop(){if(app&&app.exitCode===null){const stopped=new Promise(r=>app.once('exit',r));app.kill('SIGTERM');await stopped}}
async function ready(){for(let i=0;i<100;i++){try{if((await fetch(origin)).ok)return}catch{}await new Promise(r=>setTimeout(r,100))}throw new Error('App did not start: '+logs)}
let count=0;async function check(name,work){await work();count++;console.log('PASS',name)}
async function request(path,{method='GET',body,cookie='',requestOrigin=origin}={}){const r=await fetch(origin+path,{method,headers:{Origin:requestOrigin,'Content-Type':'application/json',Cookie:cookie},body:body===undefined?undefined:JSON.stringify(body)});let data;try{data=await r.json()}catch{data=null}return {status:r.status,data,cookie:r.headers.get('set-cookie')?.split(';')[0],headers:r.headers}}
const credentials=name=>({displayName:name,email:name+'@example.test',password:'test-password-2026!',acceptTerms:true});
const passport=(name,visibility='PRIVATE',discoveryOptIn=false)=>({displayName:name,roles:['Controller'],languages:['Hindi','English'],rank:'Diamond',intent:'Competitive',agents:'Omen, Clove',start:1260,end:60,visibility,discoveryOptIn});
async function token(email,purpose){const messages=(await readFile(mailFile,'utf8')).trim().split('\n').filter(Boolean).map(s=>JSON.parse(s));const mail=messages.findLast(x=>x.to.includes(email)&&x.subject.includes(purpose==='VERIFY'?'Verify':'Reset'));assert.ok(mail,'Email captured');const url=new URL(mail.text.match(/http[^\s]+/)[0]);assert.equal(url.search,'');return new URLSearchParams(url.hash.slice(1)).get('token')}
async function verify(email){return request('/api/account/verify',{method:'POST',body:{token:await token(email,'VERIFY')}})}
try{
 start();await ready();
 await check('public review, demo and policies work without signup or Riot credentials',async()=>{for(const route of ['/review','/demo','/privacy','/terms','/account']){const response=await fetch(origin+route);assert.equal(response.status,200);const html=await response.text();assert.match(html,/Valo/)}assert.equal((await request('/api/health')).status,200);const html=await (await fetch(origin+'/demo')).text();assert.match(html,/fictional/i)});
 await check('private endpoints reject unauthenticated access',async()=>{for(const path of ['/api/profile','/api/discover','/api/lfg','/api/account/export','/api/moderation'])assert.equal((await request(path)).status,401)});
 await check('signup requires policy acceptance',async()=>assert.equal((await request('/api/auth/signup',{method:'POST',body:{...credentials('terms'),acceptTerms:false}})).status,400));
 let a,b;
 await check('signup creates private profile, records policy and emits hashed email token',async()=>{a=await request('/api/auth/signup',{method:'POST',body:credentials('alpha')});assert.equal(a.status,201,JSON.stringify(a.data));assert.match(a.headers.get('set-cookie'),/HttpOnly/i);const profile=await request('/api/profile',{cookie:a.cookie});assert.equal(profile.data.passport.visibility,'PRIVATE');assert.equal(profile.data.passport.discoveryOptIn,false);assert.equal(profile.data.emailVerified,false);const {rows}=await db.query('SELECT "termsAcceptedAt","policyVersion" FROM "User" WHERE email=\'alpha@example.test\'');assert.equal(rows[0].policyVersion,'2026-10-03');assert.ok(rows[0].termsAcceptedAt);const raw=await token('alpha@example.test','VERIFY');const {rows:tokens}=await db.query('SELECT "tokenHash" FROM "AccountToken"');assert.ok(tokens.every(x=>x.tokenHash!==raw));assert.ok(!JSON.stringify(a.data).includes(raw))});
 await check('unverified account can save privately but cannot share, discover or post',async()=>{assert.equal((await request('/api/profile',{method:'PUT',cookie:a.cookie,body:passport('Alpha')})).status,200);assert.equal((await request('/api/profile',{method:'PUT',cookie:a.cookie,body:passport('Alpha','PUBLIC',true)})).status,403);assert.equal((await request('/api/discover',{cookie:a.cookie})).status,403);assert.equal((await request('/api/lfg',{cookie:a.cookie})).status,403);assert.equal((await request('/api/lfg',{method:'POST',cookie:a.cookie,body:{title:'Looking for a sentinel',rolesNeeded:['Sentinel']}})).status,403)});
 await check('email verification is single use and never verifies Riot identity',async()=>{const raw=await token('alpha@example.test','VERIFY');assert.equal((await verify('alpha@example.test')).status,200);assert.equal((await request('/api/account/verify',{method:'POST',body:{token:raw}})).status,400);assert.equal((await request('/api/profile',{cookie:a.cookie})).data.emailVerified,true);assert.deepEqual((await db.query('SELECT * FROM "RiotLink"')).rows,[])});
 await check('legacy accounts must accept current policies before sharing',async()=>{const uid=(await request('/api/profile',{cookie:a.cookie})).data.passport.userId;await db.query('UPDATE "User" SET "policyVersion"=NULL WHERE id=$1',[uid]);assert.equal((await request('/api/profile',{method:'PUT',cookie:a.cookie,body:passport('Alpha','PUBLIC',true)})).status,403);assert.equal((await request('/api/account/accept-policies',{method:'POST',cookie:a.cookie,body:{acceptTerms:false}})).status,400);assert.equal((await request('/api/account/accept-policies',{method:'POST',cookie:a.cookie,body:{acceptTerms:true}})).status,200)});
 await check('second independent verified signup',async()=>{b=await request('/api/auth/signup',{method:'POST',body:credentials('bravo')});assert.equal(b.status,201);assert.equal((await verify('bravo@example.test')).status,200);assert.equal((await request('/api/profile',{method:'PUT',cookie:b.cookie,body:passport('Bravo')})).status,200)});
 await check('private and public without discovery stay hidden',async()=>{assert.deepEqual((await request('/api/discover',{cookie:a.cookie})).data,[]);assert.equal((await request('/api/profile',{method:'PUT',cookie:b.cookie,body:passport('Bravo','PUBLIC')})).status,200);assert.deepEqual((await request('/api/discover',{cookie:a.cookie})).data,[])});
 let bravoId;
 await check('opted-in discovery exposes public preference fields only',async()=>{await request('/api/profile',{method:'PUT',cookie:b.cookie,body:passport('Bravo','PUBLIC',true)});const res=await request('/api/discover',{cookie:a.cookie});assert.equal(res.data.length,1);bravoId=res.data[0].player.id;assert.equal(res.data[0].match.overlap,240);for(const secret of ['example.test','passwordHash','termsAcceptedAt','emailVerifiedAt'])assert.ok(!JSON.stringify(res.data).includes(secret))});
 let post;
 await check('LFG persists and owner is enforced',async()=>{post=await request('/api/lfg',{method:'POST',cookie:b.cookie,body:{title:'Open qualifier practice group',rolesNeeded:['Sentinel']}});assert.equal(post.status,201);assert.equal((await request('/api/lfg',{cookie:a.cookie})).data.length,1);assert.equal((await request('/api/lfg',{method:'DELETE',cookie:a.cookie,body:{id:post.data.id}})).status,404)});
 await check('reports save privately without public penalties',async()=>{assert.equal((await request('/api/moderation',{method:'POST',cookie:a.cookie,body:{action:'report',subjectId:bravoId,reason:'A test concern requiring manual review.'}})).status,201);assert.equal((await db.query('SELECT * FROM "Report"')).rows.length,1);assert.equal((await request('/api/discover',{cookie:a.cookie})).data.length,1)});
 await check('blocking hides both players and LFG; unblock restores eligibility',async()=>{await request('/api/profile',{method:'PUT',cookie:a.cookie,body:passport('Alpha','PUBLIC',true)});assert.equal((await request('/api/discover',{cookie:b.cookie})).data.length,1);assert.equal((await request('/api/moderation',{method:'POST',cookie:a.cookie,body:{action:'block',subjectId:bravoId}})).status,200);assert.deepEqual((await request('/api/discover',{cookie:a.cookie})).data,[]);assert.deepEqual((await request('/api/discover',{cookie:b.cookie})).data,[]);assert.deepEqual((await request('/api/lfg',{cookie:a.cookie})).data,[]);assert.equal((await request('/api/moderation',{cookie:a.cookie})).data.length,1);await request('/api/moderation',{method:'POST',cookie:a.cookie,body:{action:'unblock',subjectId:bravoId}});assert.equal((await request('/api/discover',{cookie:a.cookie})).data.length,1)});
 await check('server ownership ignores client user ID',async()=>{assert.equal((await request('/api/profile',{method:'PUT',cookie:a.cookie,body:{...passport('Alpha updated'),userId:bravoId}})).status,200);assert.equal((await request('/api/profile',{cookie:b.cookie})).data.displayName,'Bravo')});
 await check('privacy revocation immediately hides Passport and posts',async()=>{await request('/api/profile',{method:'PUT',cookie:b.cookie,body:passport('Bravo')});assert.deepEqual((await request('/api/discover',{cookie:a.cookie})).data,[]);assert.deepEqual((await request('/api/lfg',{cookie:a.cookie})).data,[])});
 await check('input validation and CSRF cover profile and account deletion',async()=>{assert.equal((await request('/api/profile',{method:'PUT',cookie:a.cookie,body:{...passport('Alpha'),roles:['Invalid']}})).status,400);assert.equal((await request('/api/profile',{method:'PUT',cookie:a.cookie,body:passport('Alpha'),requestOrigin:'https://other.test'})).status,400);assert.equal((await request('/api/account/delete',{method:'POST',cookie:a.cookie,body:{password:credentials('alpha').password,confirmation:'DELETE'},requestOrigin:'https://other.test'})).status,400)});
 await check('export includes only own account data without hashes or tokens',async()=>{const res=await request('/api/account/export',{cookie:a.cookie});assert.equal(res.status,200);assert.match(res.headers.get('content-disposition'),/attachment/);assert.equal(res.data.account.email,'alpha@example.test');for(const secret of ['bravo@example.test','passwordHash','tokenHash'])assert.ok(!JSON.stringify(res.data).includes(secret))});
 await check('disconnect removes stored link, match data and discovery',async()=>{const uid=(await request('/api/profile',{cookie:b.cookie})).data.passport.userId;await db.query('INSERT INTO "RiotLink" (id,"userId",puuid,"consentedAt") VALUES ($1,$2,$3,NOW())',['test-link',uid,'test-only-puuid']);await db.query('INSERT INTO "MatchSummary" (id,"riotLinkId","matchId","agentId","playedAt","roundsPlayed",summary) VALUES ($1,$2,$3,$4,NOW(),1,$5)',['test-match','test-link','match','agent','{}']);assert.equal((await request('/api/account/disconnect',{method:'POST',cookie:b.cookie,body:{}})).status,200);assert.deepEqual((await db.query('SELECT * FROM "MatchSummary"')).rows,[]);assert.deepEqual((await db.query('SELECT * FROM "RiotLink"')).rows,[])});
 await check('recovery has non-enumerating response and expires',async()=>{const exists=await request('/api/account/forgot',{method:'POST',body:{email:'bravo@example.test'}});const unknown=await request('/api/account/forgot',{method:'POST',body:{email:'unknown@example.test'}});assert.deepEqual(exists.data,unknown.data);const raw=await token('bravo@example.test','RESET');await db.exec('UPDATE "AccountToken" SET "expiresAt"=NOW()-INTERVAL \'1 day\' WHERE purpose=\'RESET\'');assert.equal((await request('/api/account/reset',{method:'POST',body:{token:raw,password:'changed-password-2026!'}})).status,400)});
 await check('recovery works once and revokes all sessions',async()=>{await request('/api/account/forgot',{method:'POST',body:{email:'bravo@example.test'}});const raw=await token('bravo@example.test','RESET');assert.equal((await request('/api/account/reset',{method:'POST',body:{token:raw,password:'changed-password-2026!'}})).status,200);assert.equal((await request('/api/account/reset',{method:'POST',body:{token:raw,password:'another-password-2026!'}})).status,400);assert.equal((await request('/api/profile',{cookie:b.cookie})).status,401);const login=await request('/api/auth/login',{method:'POST',body:{...credentials('bravo'),password:'changed-password-2026!'}});assert.equal(login.status,200);b=login});
 await check('delivery failure does not expose tokens; resend can recover',async()=>{await writeFile(modeFile,'fail');const res=await request('/api/auth/signup',{method:'POST',body:credentials('charlie')});assert.equal(res.status,201);assert.equal((await db.query('SELECT * FROM "AccountToken" WHERE "userId"=(SELECT id FROM "User" WHERE email=\'charlie@example.test\')')).rows.length,0);await writeFile(modeFile,'ok');assert.equal((await request('/api/account/resend',{method:'POST',cookie:res.cookie,body:{}})).status,200);assert.equal((await verify('charlie@example.test')).status,200)});
 await check('operator suspension blocks active sessions and new login',async()=>{const login=await request('/api/auth/login',{method:'POST',body:credentials('charlie')});const uid=(await request('/api/profile',{cookie:login.cookie})).data.passport.userId;await db.query('UPDATE "User" SET "suspendedAt"=NOW() WHERE id=$1',[uid]);assert.equal((await request('/api/profile',{cookie:login.cookie})).status,401);assert.equal((await request('/api/auth/login',{method:'POST',body:credentials('charlie')})).status,403)});
 await check('verification expiration is enforced',async()=>{const res=await request('/api/auth/signup',{method:'POST',body:credentials('delta')});assert.equal(res.status,201);await db.exec('UPDATE "AccountToken" SET "expiresAt"=NOW()-INTERVAL \'1 day\'');assert.equal((await verify('delta@example.test')).status,400)});
 await check('deletion needs current password and removes related active data',async()=>{assert.equal((await request('/api/account/delete',{method:'POST',cookie:b.cookie,body:{password:'incorrect-password-long',confirmation:'DELETE'}})).status,401);assert.equal((await request('/api/account/delete',{method:'POST',cookie:b.cookie,body:{password:'changed-password-2026!',confirmation:'NO'}})).status,400);assert.equal((await request('/api/account/delete',{method:'POST',cookie:b.cookie,body:{password:'changed-password-2026!',confirmation:'DELETE'}})).status,200);assert.equal((await request('/api/profile',{cookie:b.cookie})).status,401);assert.equal((await db.query('SELECT * FROM "User" WHERE email=\'bravo@example.test\'')).rows.length,0);assert.equal((await db.query('SELECT * FROM "LFGPost" WHERE "authorId"=$1',[bravoId])).rows.length,0);assert.equal((await db.query('SELECT * FROM "Report" WHERE "subjectId"=$1',[bravoId])).rows.length,0)});
 await check('logout and session expiration enforced',async()=>{assert.equal((await request('/api/auth/logout',{method:'POST',cookie:a.cookie,body:{}})).status,200);assert.equal((await request('/api/profile',{cookie:a.cookie})).status,401);const login=await request('/api/auth/login',{method:'POST',body:credentials('alpha')});assert.equal(login.status,200);await db.exec('UPDATE "Session" SET "expiresAt"=NOW()-INTERVAL \'1 day\'');assert.equal((await request('/api/profile',{cookie:login.cookie})).status,401)});
 await check('email-scoped login throttling enforced',async()=>{let last;for(let i=0;i<11;i++)last=await request('/api/auth/login',{method:'POST',body:{email:'missing@example.test',password:'wrong-password-long'}});assert.equal(last.status,429)});
 await check('signup stays closed when operator details are missing; demo still works',async()=>{await stop();start({OPERATOR_NAME:''});await ready();assert.equal((await request('/api/auth/signup',{method:'POST',body:credentials('closed')})).status,503);assert.equal((await fetch(origin+'/demo')).status,200)});
 await check('secure HTTPS deployment cookies are enabled',async()=>{await stop();start({COOKIE_SECURE:'true'});await ready();const login=await request('/api/auth/login',{method:'POST',body:credentials('alpha')});assert.equal(login.status,200);assert.match(login.headers.get('set-cookie'),/Secure/);assert.match(login.headers.get('set-cookie'),/SameSite=lax/i)});
 console.log(`${count} integration checks passed. Email transport was intercepted; no external messages sent.`);
}catch(e){console.error(logs);throw e}finally{await stop();await server.stop();await new Promise(r=>setTimeout(r,100));await db.close();await rm(temp,{recursive:true,force:true})}
